# Generated by Django 4.1.3 on 2022-11-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uit_app', '0002_department_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['?']},
        ),
    ]
