# Generated by Django 4.1.3 on 2022-11-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uit_app', '0004_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department_code',
            field=models.CharField(default='66', max_length=30),
        ),
    ]
