# Generated by Django 4.1.3 on 2022-11-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uit_app', '0005_student_department_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department_code',
            field=models.CharField(max_length=30),
        ),
    ]
