# Generated by Django 4.1.3 on 2022-11-30 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uit_app', '0006_alter_student_department_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department_code',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uit_app.department'),
        ),
    ]
